config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'home#home'

  # Default resource routes
  resources :room_messages
  resources :rooms
  resources :goals
  resources :room_messages
  resources :rooms
  resources :leaderboards

  # Custom + default routes for habits
  resources :habits do
    post :track, on: :member
    post :reset_streak, on: :member
    post :reset_max_streak, on: :member
    resources :schedules
  end


  # Custom routes for goals
  get 'completed', to: 'goals#completed'
  get 'createBaseGoals', to: 'goals#createBaseGoals'
  get 'createHabitGoals', to: 'goals#createHabitGoals'
  get 'goals', to: 'goals#index'
  get 'updateGoals', to: 'goals#updateGoals'

  # Devise routes for user auth
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Routes for legal stuff
  get 'policy/privacy' => 'legal#privacy'
  get 'policy/security'=> 'legal#security'
  get 'policy/cookie-notice'=> 'legal#cookieInfo'
  post '/push'=> 'home#push'

  # API routes that are required for react to work
  namespace :api do
    namespace :v1 do
      get 'habits/index' => 'habits#index'
      get 'habits/show' => 'habits#show'
      post 'habits/push_notification' => 'habits#push_notification'
      post 'habits/add_push_endpoint' => 'habits#add_push_endpoint'
    end
  end

  # Custom routes for leaderboards
  post 'joinWcode', to: 'leaderboards#join'

  # Custom routes for leaderboard invites
  post 'leaveBoard', to: 'invites#leave'
  post 'inviteUser', to: 'invites#invite'
  post 'acceptInvite', to: 'invites#accept'
  post 'rejectInvite', to: 'invites#reject'


end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  has_many :board_users, dependent: :destroy
  has_many :users, through: :board_users

  has_one :room, inverse_of: :leaderboard

  validates :title, presence: true
  validates :description, presence: true

  validates :title, length: { in: 4..20 }
  validates :title, format: { with: /\A[\s0-9a-zA-Z]+\z/,
    message: "Only allows letters, integers and whitespaces" }\

  validates :description, format: { with: /\A[\s0-9a-zA-Z]+\z/,
    message: "Only allows letters, integers and whitespaces" }
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: %i[ show edit update destroy ]
  before_action :user_check, only: %i[ show edit update destroy ]

  # GET /leaderboards
  def index
    @leaderboards = Leaderboard.where(board_users: BoardUser.where(user: current_user, status: "accepted"))
  end

  # GET /leaderboards/1/
  def show
    @leaderboard = Leaderboard.find(params[:id])
    @room = Room.find(@leaderboard.room_id)
  end

  # GET /leaderboards/new/
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)
    @room = Room.new(leaderboard: @leaderboard)
    @room.save

    @leaderboard.board_users.new(user: current_user, status:"accepted")
    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: "Leaderboard was successfully created." }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1 or /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to @leaderboard, notice: "Leaderboard was successfully updated." }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @leaderboard = Leaderboard.find(params[:id])
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: "Leaderboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /joinWcode
  def join
    unless params[:code].nil?
      code = params[:code]
      parts = code.split('|')
      lbID = parts.first
      usrID = parts.last

      @tgtLb = Leaderboard.find(lbID)
      unless @tgtLb.nil?
        #If the leaderboard exists and the usrID exists on the leaderboard
        #add current user to the leaderboard
        unless @tgtLb.users.find(usrID).nil?
          entry = current_user.board_users.new(user: current_user, leaderboard: @tgtLb,status:"accepted")
          if entry.save!
            flash.notice ="Leaderboard was successfully joined."
            redirect_back(fallback_location: leaderboards_path)
          end
        end
      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      if Leaderboard.exists?(params[:id])
      @leaderboard = Leaderboard.find(params[:id])
      else
        redirect_to leaderboards_url, notice: "Sorry, that leaderboard does not exist."
        end
    end

    # Only allow a list of trusted parameters through.
    def leaderboard_params
      params.require(:leaderboard).permit(:title, :description)
    end
  def user_check
    if !(@leaderboard.user_ids.include?(current_user.id))
      redirect_to leaderboards_url, notice: "Sorry, but you are only allowed to view the leaderboards you are currently in."
    end
  end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
  # Helper methods for leaderboards

  # Get user score based on sum of all their streaks
  def calc_score(user, leaderboard)
    temp = leaderboard.board_users.find_by(user: user)
    @new_score = 0
    @old_score = temp.score
    user.habits.each_with_index do |habit, i|
      @new_score = @new_score + habit.streak
    end
    if @new_score != @old_score
      temp.score = @new_score
      temp.save!
    end
  end

  # Get user by id?
  def get_user(userid)
    @user = User.find_by_id(userid)
  end

  # Sort user in a leaderboard
  def sort_users(leaderboard)
    @users = User.where(board_users: BoardUser.where(leaderboard: leaderboard, status: "accepted"))
    @users.each{|u| calc_score(u,leaderboard)}
    @users.sort_by{|u| leaderboard.board_users.find_by(user: u).score}.reverse!
  end

  # Returns all users in a leaderboard
  def get_all_users(leaderboard)
    @users = User.all
    @leaderboard.user_ids = []
    @users.each do |user|
      @leaderboard.user_ids = @leaderboard.user_ids<< user.id
    end
  end
end

app/views/leaderboards/_form.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body rounded d-flex justify-content-center"></div>
        <%= form_with(model: leaderboard, local: true) do |form| %>
          <div class="field form-group w-100">
            <div class="form-inline">
              <%= form.label :title, t('.leaderboard_title'), :class => "col-form-label" %><br>
              <%= form.text_field :title, :class => "form-control", :placeholder => t('.title_placeholder'), :size => 40 %>
            </div>
          </div>

          <div class="field form-group w-100">
            <%= form.label :description, t('.habit_desc'), :class => "col-form-label" %><br>
            <%= form.text_area :description, :class => "form-control", :placeholder => t('.description_placeholder'), :rows => 3 %>
          </div>

          <div class="actions">
            <%= form.submit "Create", :class => "float-left btn btn-info btn-md" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<div class="container-md">
  <h2><%= t(".active_leaderboards") %></h2>
  <table class = "table table-striped table-dark">
    <thead class = "thead-light">
      <tr>
        <th><%= t(".title") %></th><th><%= t(".interactions") %></th><th></th><th></th>
      </tr>
    </thead>
    <tbody>
      <% @leaderboards.each do |leaderboard| %>
        <tr>
          <td>
            <%= leaderboard.title %>
          </td>
          <td><%= link_to 'Show', leaderboard %></td>
          <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
          <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <br>
  <%= link_to 'New Leaderboard', new_leaderboard_path %>
  <br>
  <hr>
  <h2>Join a leaderboard</h2>
  <%=form_tag joinWcode_path, method: :post do%>
    <%= label_tag("Invite Code") %>
    <%= text_field_tag('code')%>
    <%= submit_tag("Join")%>
  <%end %>
  <hr>
  <%invites = BoardUser.where(status: "pending", user_id:current_user.id) %>
  <%unless invites.empty?%>
    <h2>Pending Invites</h2>
    <table>
      <th>Name</th><th>Description</th> <th></th> <th></th>
      <%invites.each do |invite|%>
        <tr>
          <td><h6><%=invite.leaderboard.title%></h6></td>
          <td><h6><%=invite.leaderboard.description%></h6></td>
          <td><%=button_to "Accept", acceptInvite_path, method: :post, class:"btn btn-info",
                           params: {:id => invite.id}%></td>
          <td><%=button_to "Reject", rejectInvite_path, method: :post, class:"btn btn-info",
                           params: {:id => invite.id}%></td>
        </tr>
      <%end%>
    </table>
  <%end%>
</div>

app/views/leaderboards/new.html.erb
<div class="container-md">
  <div class="container text-center custom-page-heading">
    <%= link_to t('.back'), leaderboards_path, :class => "btn float-left habit-back-btn" %>
    <h1><%= t(".new_leaderboard") %></h1>
  </div>
  <%= render 'form', leaderboard: @leaderboard %>
</div>

app/views/leaderboards/show.html.erb
<div class="container-md">
  <h1><%=@room.leaderboard.title%></h1>
  <h3><%=@leaderboard.description%></h3>
  <%= link_to t('.leaderboard_chat'), room_path(@room), class: 'btn btn-info btn-md' %>
  <table class="table table-striped table-dark">
    <thead>
    <tr>
      <th>Rank</th><th></th><th>Name</th><th>Score</th>
    </tr>
    </thead>
    <tbody>
    <%if @leaderboard == Leaderboard.find_by_id(0)%>
      <%get_all_users(@leaderboard) %>
      <%end %>
    <%@users = sort_users(@leaderboard) %>
    <% @users.each_with_index do |user,i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td>
          <%unless user.image.nil?%>
            <%= image_tag user.image %>
          <%end %>
        </td>
        <td>
          <%if user.name.nil?%>
            <%= user.email%>
          <%else %>
            <%= user.name %>
          <%end %>
        </td>
        <td>
          <%=
            score = @leaderboard.board_users.find_by(user: user).score
            if score.nil?
              0
            else
              score
            end
          %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <hr>
  <%unless current_user.auths.empty? %>
    <h3>Invite Your Friends</h3>
    <table>
      <th></th><th></th>
      <%data = User.get_friends(session[:fb_token])%>
      <%data.each do |person|%>
        <tr>
          <td><h5><%=person['name'] %></h5></td>
          <td><%=button_to "Invite", inviteUser_path, method: :post, class:"btn btn-info",
                           params: {:name => person['name'], :leaderboard => @leaderboard.id}%></td>
        </tr>
      <%end%>
    </table>
  <%end %>
  <button class="btn btn-info codeGen-button"> Generate Invite Code </button>
  <script>
      let lbID = <%=@leaderboard.id.to_s%>;
      let lbTitle = "<%=@leaderboard.title.to_s%>";
      let gener = <%=current_user.id.to_s.to_s%>;
      $(document).ready(function(){
          $(".codeGen-button").on("click", e => {
              if(lbTitle.length > 10){lbTitle = lbTitle.substring(0,10)}
              let invCode = (lbID+"|"+lbTitle+"|"+gener).toString();
              $(".InvCode").text("Your Invite Code is: "+invCode);
          })
      })
  </script>
  <h3 class="InvCode"></h3>
  <%=button_to "Leave the Board", leaveBoard_path, method: :post, class:"btn btn-info",
               params: {:id => @leaderboard.id}%>
</div>