config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'home#home'

  # Default resource routes
  resources :room_messages
  resources :rooms
  resources :goals
  resources :room_messages
  resources :rooms
  resources :leaderboards

  # Custom + default routes for habits
  resources :habits do
    post :track, on: :member
    post :reset_streak, on: :member
    post :reset_max_streak, on: :member
    resources :schedules
  end


  # Custom routes for goals
  get 'completed', to: 'goals#completed'
  get 'createBaseGoals', to: 'goals#createBaseGoals'
  get 'createHabitGoals', to: 'goals#createHabitGoals'
  get 'goals', to: 'goals#index'
  get 'updateGoals', to: 'goals#updateGoals'

  # Devise routes for user auth
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Routes for legal stuff
  get 'policy/privacy' => 'legal#privacy'
  get 'policy/security'=> 'legal#security'
  get 'policy/cookie-notice'=> 'legal#cookieInfo'
  post '/push'=> 'home#push'

  # API routes that are required for react to work
  namespace :api do
    namespace :v1 do
      get 'habits/index' => 'habits#index'
      get 'habits/show' => 'habits#show'
      post 'habits/push_notification' => 'habits#push_notification'
      post 'habits/add_push_endpoint' => 'habits#add_push_endpoint'
    end
  end

  # Custom routes for leaderboards
  post 'joinWcode', to: 'leaderboards#join'

  # Custom routes for leaderboard invites
  post 'leaveBoard', to: 'invites#leave'
  post 'inviteUser', to: 'invites#invite'
  post 'acceptInvite', to: 'invites#accept'
  post 'rejectInvite', to: 'invites#reject'


end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :habit

  validates :habit_id, presence: true
  validates :date, presence: true
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  validate :DurationViable?

  def DurationViable?
    return if [starts_at.blank?, ends_at.blank?].any?
    if starts_at > ends_at
      errors.add(:starts_at, 'must be before end time')
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]
  before_action :get_habit
  # GET /schedules or /schedules.json
  def index
    @schedules = @habit.schedules
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = @habit.schedules.build
      #unless current_user.auths.where(provider: "google_oauth2").empty?
      #cal = Google::Calendar.new(:client_id     => ENV[:GOOGLE_CLIENT_ID],
      #                           :client_secret => ENV[:GOOGLE_CLIENT_SECRET],
      #                           :calendar      => "default",
      #                           :redirect_url  => "urn:ietf:wg:oauth:2.0:oob" # this is what Google uses for 'applications'
      #)
      #cal.login_with_refresh_token(session[:gg_token])
      #@events = cal.events
      #    end
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = @habit.schedules.build(schedule_params)
    @schedule.habit_id = @habit.id
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to habit_schedules_path(@habit), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to habit_schedules_path(@habit), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to habit_schedules_path(@habit), notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_habit
      @habit = Habit.find(params[:habit_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @habit = Habit.find(params[:habit_id])
      @schedule = @habit.schedules.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:habit_id, :date, :starts_at, :ends_at)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body rounded d-flex justify-content-center"></div>
          <%= form_with(model: [@habit, schedule], local: true) do |form| %>
            <% if schedule.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>
                <ul>
                <% schedule.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.label :date %>
              <%= form.date_select :date %>
            </div>

            <div class="field">
              <%= form.label :starts_at, "Start time" %>
              <%= form.time_select :starts_at %>
            </div>

            <div class="field">
              <%= form.label :ends_at, "Finish time" %>
              <%= form.time_select :ends_at %>
            </div>

            <div class="actions">
              <%= form.submit %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/edit.html.erb
<div class="container text-center custom-page-heading">
  <%= link_to t('.back'), habit_schedules_path(@habit), :class => "btn float-left habit-back-btn" %>
  <h1>Editing Schedule for <%=@habit.title%></h1>
</div>
<%= render 'form', schedule: @schedule %>

app/views/schedules/index.html.erb
<div class="container text-center custom-page-heading">
  <%= link_to t('.back'), root_path, :class => "btn float-left habit-back-btn" %>
  <h1>Your schedule for <%=@habit.title%></h1>
</div>
<div class="container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">

            <%=button_to ("New Schedule"), new_habit_schedule_path, method: :get,class:"btn btn-info btn-md"%>

            <br>
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Start</th>
                  <th>End</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @schedules.each do |schedule| %>
                <tr>
                  <td><%= schedule.date %></td>
                  <td><%= schedule.starts_at.strftime("%H:%M") %></td>
                  <td><%= schedule.ends_at.strftime("%H:%M") %></td>

                  <td><%= link_to 'Edit', edit_habit_schedule_path(@habit, schedule) %></td>
                  <td><%= link_to 'Destroy', [@habit, schedule], method: :delete, data: { confirm: t('confirm') } %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
      </div>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="container text-center custom-page-heading">
  <%= link_to t('.back'), root_path, :class => "btn float-left habit-back-btn" %>
  <h1>New Schedule for <%=@habit.title%></h1>
</div>

<%= render 'form', schedule: @schedule %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Habit:</strong>
  <%= @schedule.habit_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Start:</strong>
  <%= @schedule.starts_at.strftime("%H:%M") %>
</p>

<p>
  <strong>End:</strong>
  <%= @schedule.ends_at.strftime("%H:%M") %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>