config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'home#home'

  # Default resource routes
  resources :room_messages
  resources :rooms
  resources :goals
  resources :room_messages
  resources :rooms
  resources :leaderboards

  # Custom + default routes for habits
  resources :habits do
    post :track, on: :member
    post :reset_streak, on: :member
    post :reset_max_streak, on: :member
    resources :schedules
  end


  # Custom routes for goals
  get 'completed', to: 'goals#completed'
  get 'createBaseGoals', to: 'goals#createBaseGoals'
  get 'createHabitGoals', to: 'goals#createHabitGoals'
  get 'goals', to: 'goals#index'
  get 'updateGoals', to: 'goals#updateGoals'

  # Devise routes for user auth
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Routes for legal stuff
  get 'policy/privacy' => 'legal#privacy'
  get 'policy/security'=> 'legal#security'
  get 'policy/cookie-notice'=> 'legal#cookieInfo'
  post '/push'=> 'home#push'

  # API routes that are required for react to work
  namespace :api do
    namespace :v1 do
      get 'habits/index' => 'habits#index'
      get 'habits/show' => 'habits#show'
      post 'habits/push_notification' => 'habits#push_notification'
      post 'habits/add_push_endpoint' => 'habits#add_push_endpoint'
    end
  end

  # Custom routes for leaderboards
  post 'joinWcode', to: 'leaderboards#join'

  # Custom routes for leaderboard invites
  post 'leaveBoard', to: 'invites#leave'
  post 'inviteUser', to: 'invites#invite'
  post 'acceptInvite', to: 'invites#accept'
  post 'rejectInvite', to: 'invites#reject'


end

app/views/shared/_footer.html.erb
<div style="position: fixed; bottom: 0; left: 0; right: 0; background:#343A40; color: white;text-align:center;">
  <%=link_to "Cookie Policy", policy_cookie_notice_path%> |
  <%=link_to "Privacy Policy", policy_privacy_path%> |
  <%=link_to "Security Policy", policy_security_path%>
</div>

app/views/shared/_header.html.erb
<div class="page-header navbar navbar-expand-md bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
        <%=t('app_title') %>
    </span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarToggle">
    <ul class="navbar-nav">
      <li class="nav-item mr-2"><%=button_to t('.action_goals'), goals_path, method: :get,class:"btn btn-info btn-md"%></li>
      <li class="nav-item mr-2"><%=button_to t('.action_lead'), leaderboards_path, method: :get,class:"btn btn-info btn-md"%></li>
      <li class="nav-item"><%=button_to t('.action_rooms'), rooms_path, method: :get,class:"btn btn-info btn-md"%></li>
    </ul>

    <a class="navbar-brand" href="/">
      <%=t('app_title') %>
    </a>

    <ul class="navbar-nav">
      <li class="nav-item">
        <div class="nav-link" style="color: white">
          <% if user_signed_in? %>
            <%unless current_user.name.nil? %>
              <%= "#{current_user.name} |" %>
            <%else %>
              <%= "#{current_user.email} |" %>
            <%end%>
            <%unless current_user.image.nil? %>
              <%= link_to image_tag(current_user.image), edit_user_registration_path %>
            <%else %>
              <%= link_to icon('fas', 'user-alt fa-lg'), edit_user_registration_path %>
            <%end %>
            <%= '|' %>
            <%= link_to icon('fas', 'sign-out-alt fa-lg'), destroy_user_session_path, method: 'delete' %>
          <% else %>
            <%= link_to icon('fas', 'sign-in-alt fa-lg'), new_user_session_path %>
            <%= '|' %>
            <%= link_to icon('fas', 'user-plus fa-lg'), new_user_registration_path %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>