config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'home#home'

  # Default resource routes
  resources :room_messages
  resources :rooms
  resources :goals
  resources :room_messages
  resources :rooms
  resources :leaderboards

  # Custom + default routes for habits
  resources :habits do
    post :track, on: :member
    post :reset_streak, on: :member
    post :reset_max_streak, on: :member
    resources :schedules
  end


  # Custom routes for goals
  get 'completed', to: 'goals#completed'
  get 'createBaseGoals', to: 'goals#createBaseGoals'
  get 'createHabitGoals', to: 'goals#createHabitGoals'
  get 'goals', to: 'goals#index'
  get 'updateGoals', to: 'goals#updateGoals'

  # Devise routes for user auth
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Routes for legal stuff
  get 'policy/privacy' => 'legal#privacy'
  get 'policy/security'=> 'legal#security'
  get 'policy/cookie-notice'=> 'legal#cookieInfo'
  post '/push'=> 'home#push'

  # API routes that are required for react to work
  namespace :api do
    namespace :v1 do
      get 'habits/index' => 'habits#index'
      get 'habits/show' => 'habits#show'
      post 'habits/push_notification' => 'habits#push_notification'
      post 'habits/add_push_endpoint' => 'habits#add_push_endpoint'
    end
  end

  # Custom routes for leaderboards
  post 'joinWcode', to: 'leaderboards#join'

  # Custom routes for leaderboard invites
  post 'leaveBoard', to: 'invites#leave'
  post 'inviteUser', to: 'invites#invite'
  post 'acceptInvite', to: 'invites#accept'
  post 'rejectInvite', to: 'invites#reject'


end

app/models/habit.rb
class Habit < ApplicationRecord
  before_save :default_values
  belongs_to  :user
  has_many :schedules, dependent: :destroy

  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true

  validates :title, length: { in: 4..20 }
  validates :title, format: { with: /\A[\s0-9a-zA-Z]+\z/,
    message: "Only allows letters, integers and whitespaces" }\

  validates :description, format: { with: /\A[\s0-9a-zA-Z]+\z/,
    message: "Only allows letters, integers and whitespaces" }

  validates :streak, numericality: { greater_than: -1 }
  validates :target, numericality: { greater_than: 4 }

  # set target to 60 by default
  def default_values
    self.target = 60 if self.target.nil?
    self.last_tracked = DateTime.now
  end
end

app/controllers/api/v1/habits_controller.rb
require 'webpush'

module Api
  module V1
    class HabitsController < ApplicationController
      skip_before_action :verify_authenticity_token

      def index
        unless current_user.nil?
          habits = Habit.find_by_user_id(current_user)
        else
          habits = Habit.find_by_user_id(params[:user_id])
        end
        render json: HabitSerializer.new(habits).serialized_json
      end


      def show
        habit = Habit.find_by(id: params[:id])
        render json: HabitSerializer.new(habit).serialized_json
      end

      # POST api/v1/habits/add_push_endpoint
      # gets endpoint it and stores it in database
      # so that users can get notifications specific to them on all their devices
      # (by default subscription is related to specific browser and not user
      # so one user can have multiple subscriptions)
      def add_push_endpoint
        if PushSubscription.where(endpoint: params[:subscription][:endpoint]).empty?
          @subscription = PushSubscription.new(
            endpoint: params[:subscription][:endpoint],
            p256dh: params[:subscription][:keys][:p256dh],
            auth: params[:subscription][:keys][:auth])
          @subscription.user = current_user
          @subscription.save
        end
      end

      # POST api/v1/habits/push_notification
      # method for pushing a notifications,
      # loops through all user subscriptions and sends a payload with their email as message
      # if subscription is outdated or otherwose Invalid it is destroyed
      def push_notification
        current_user.push_subscriptions.each do |subscription| begin
          Webpush.payload_send(
            message: subscription.user.email,
            endpoint: subscription.endpoint,
            p256dh: subscription.p256dh,
            auth: subscription.auth,
            vapid: {
              subject: "mailto:sender@example.com",
              public_key: ENV['VAPID_PUBLIC_KEY'],
              private_key: ENV['VAPID_PRIVATE_KEY'],
              expiration: 60*59*24
            },
            ssl_timeout: 5, # value for Net::HTTP#ssl_timeout=, optional
            open_timeout: 5, # value for Net::HTTP#open_timeout=, optional
            read_timeout: 5 # value for Net::HTTP#read_timeout=, optional
          )
          rescue Webpush::InvalidSubscription => exception
            subscription.destroy
          rescue Webpush::ExpiredSubscription => exception
            subscription.destroy
          end
        end
      end
    end
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:edit, :update, :destroy, :track]
  before_action :user_check, only:[:edit, :update, :destroy, :track]

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = Habit.new(habit_params)
    @habit.user_id = current_user.id
    @habit.streak = 0
    @habit.max_streak = 0
    respond_to do |format|
      if @habit.save
        format.html { redirect_to :root, notice: "Habit was successfully created." }
        format.json { render :show, status: :created, location: 'home#home' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to :root, notice: "Habit was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: "Habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST hasbits/1/track
  # Increases streak for specific habit, or resets it if the streak was lost
  def track
    if @habit.last_tracked.nil? || @habit.last_tracked.to_date == Date.yesterday
      @habit.streak = @habit.streak + 1
      @habit.last_tracked = DateTime.now
      @habit.save

      respond_to do |format|
        format.html { redirect_to :root, notice: 'Good job!'  }
        format.js {}
      end
    elsif @habit.last_tracked.to_date < Date.yesterday
      @habit.streak = 1
      @habit.last_tracked = DateTime.now
      @habit.save

      respond_to do |format|
        format.html { redirect_to :root, alert: "You've lost you streak. Too bad!"  }
        format.js {}
      end
    else
      respond_to do |format|
        format.html { redirect_to :root, notice: 'You have already done that today. Come back tomorrow!'  }
      end
    end

    if @habit.max_streak.nil?
      @habit.max_streak = @habit.streak
      @habit.save
    elsif @habit.streak > @habit.max_streak

      @habit.max_streak = @habit.streak
      @habit.save
    end
  end

  def reset_streak
    @habit = Habit.find(params[:id])
    @habit.streak = 0
    @habit.save
  end

  def reset_max_streak
    @habit = Habit.find(params[:id])
    @habit.max_streak = @habit.streak
    @habit.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      if Habit.exists?(params[:id])
      @habit = Habit.find(params[:id])
      else
        redirect_to root_path, notice: "Sorry, that habit does not exist."
      end
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:title, :description, :target)
    end

    def user_check
      if current_user.id != @habit.user_id
        redirect_to root_path, notice: "Sorry, but you are only allowed to view your own habits."
      end
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
  # Helper method that updates a habit streak and make sure it is mantained
  # Requires habit as an argument
  def get_habit_streak(habit)
    if habit.last_tracked.to_date < Date.yesterday
      habit.streak = 1
      habit.last_tracked = DateTime.now
      habit.save

      unless Rails.env.test?
        flash.now[:alert] = "You've lost you streak. Too bad!"
      end
      return habit.streak
    else
      puts habit.streak
      return habit.streak
    end
  end
end

app/views/habits/_editform.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body rounded d-flex justify-content-center"></div>

          <%= form_with(model: habit, local: true) do |form| %>
            <div class="field form-group w-100">
              <div class="form-inline">
                <%= form.label :title, t('.habit_title'), :class => "col-form-label" %><br>
                <%= form.text_field :title, :class => "form-control", :placeholder => t('.title_placeholder'), :size => 40 %>
              </div>
            </div>

            <div class="field form-group w-100">
              <%= form.label :description, t('.habit_desc'), :class => "col-form-label" %><br>
              <%= form.text_area :description, :class => "form-control", :placeholder => t('.description_placeholder'), :rows => 3 %>
            </div>

            <div class="field form-group w-100">
              <div class="form-inline">
                <%= form.label :target, t('.habit_target'), :class => "col-form-label" %><br>
                <%= form.text_field :target, :class => "form-control", :placeholder => t('.target_placeholder'), :size => 20 %>
              </div>
            </div>

            <div class="actions">
                <%= form.submit "Save", :class => "float-left btn btn-info btn-md" %>
            </div>
          <% end %>

          <h6>Current Streak: <%= habit.streak %></h6>
          <%=button_to ("Reset Streak"), reset_streak_habit_path(habit), method: :post, data: { confirm: t('.delete_confirmation') }, class:"float-left btn btn-warning btn-md" %>
          <h6>Max Streak: <%= habit.max_streak %></h6>

          <%=button_to ("Reset Max Streak"), reset_max_streak_habit_path(habit), method: :post, data: { confirm: t('.delete_confirmation') }, class:"float-left btn btn-warning btn-md" %>
          <%=button_to ("Delete Habit"), @habit, method: :delete, data: { confirm: t('.delete_confirmation') }, class:"float-left btn btn-danger btn-md" %>
      </div>
    </div>
  </div>
</div>

app/views/habits/_form.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body rounded d-flex justify-content-center"></div>
          <%= form_with(model: habit, local: true) do |form| %>
            <div class="field form-group w-100">
              <div class="form-inline">
                <%= form.label :title, t('.habit_title'), :class => "col-form-label" %><br>
                <%= form.text_field :title, :class => "form-control", :placeholder => t('.title_placeholder'), :size => 40 %>
              </div>
            </div>

            <div class="field form-group w-100">
              <%= form.label :description, t('.habit_desc'), :class => "col-form-label" %><br>
              <%= form.text_area :description, :class => "form-control", :placeholder => t('.description_placeholder'), :rows => 3 %>
            </div>

            <div class="field form-group w-100">
              <div class="form-inline">
                <%= form.label :target, t('.habit_target'), :class => "col-form-label" %><br>
                <%= form.text_field :target, :class => "form-control", :placeholder => t('.target_placeholder'), :size => 20 %>
              </div>
            </div>

            <div class="actions">
              <%= form.submit "Create", :class => "float-left btn btn-info btn-md" %>
            </div>
          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/habits/_habit.html.erb
<div class="row p-3 my-3 bg-dark text-white">
  <div class="col-md-3">
    <div class="habits-index-text">
      <div class="habits-index-text">
        <span class="index-title"><%= habit.title %></span>
        <span class="index-description"><%= habit.description[0..50] %></span>
      </div>
    </div>
  </div>
  <div class="col-md-6 HabitCard" id=<%=habit.id%>>
    <%#The Script Will insert the Streak thing here %>
  </div>
  <div class="col-md-3">
    <div class="habit-index-desktop-icons-container">
      <%=button_to t('.action_track'), track_habit_path(habit), method: :post, class:"btn btn-info btn-block mb-1", :id=>"Track"+habit.id.to_s %>
      <%=button_to t('.action_sched'), habit_schedules_path(habit), method: :get, class:"btn btn-info btn-block mb-1" %>
      <%=button_to t('.action_edit'), edit_habit_path(habit), method: :get, class:"btn btn-info btn-block mb-1" %>
    </div>
    <div class="habit-index-mobile-icons-container">
      <div class="row">
        <div class="col pl-1 pr-1">
          <%=link_to raw("<i class='fas fa-edit fa-lg'></i>"), track_habit_path(habit), method: :post, class:"btn btn-info mobile-index-icon" %>
        </div>
        <div class="col pl-1 pr-1">
          <%=link_to raw("<i class='far fa-calendar-alt fa-lg'></i>"), habit_schedules_path(habit), method: :get, class:"btn btn-info mobile-index-icon" %>
        </div>
        <div class="col pl-1 pr-1">
          <%=link_to raw("<i class='fas fa-cogs fa-lg'></i>"), edit_habit_path(habit), method: :get, class:"btn btn-info mobile-index-icon" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/habits/edit.html.erb
<div class="container text-center custom-page-heading">
  <%= link_to t('.back'), root_path, :class => "btn float-left habit-back-btn" %>
  <h1>Habit Settings</h1>
</div>
<%= render 'editform', habit: @habit %>

<%= link_to 'Back', root_path %>

app/views/habits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Habits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: t('confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Habit', new_habit_path %>

app/views/habits/new.html.erb
<div class="container text-center custom-page-heading">
  <%= link_to t('.back'), root_path, :class => "btn float-left habit-back-btn" %>
  <h1><%= t('.new_habit') %></h1>
</div>
<%= render 'form', habit: @habit %>

app/views/habits/track.js.erb
$('div#habit-streak').html('<%= escape_javascript(@habit.streak) %>')